spring:
  application:
    name: helix-server
  cache:
    type: redis
    redis:
      time-to-live: PT1H30M
  datasource:
    hikari:
      housekeeping-period-ms: 120000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.onixbyte.helix.domain.entity
  type-handlers-package: com.onixbyte.helix.extension.mybatis.handler
  mapper-locations: classpath:/repository/*.xml
