spring:
  application:
    name: helix-server
  cache:
    type: redis
    redis:
      time-to-live: PT2H
  jpa:
    properties:
      hibernate:
        transaction:
          jta:
            # No need to use distributed transaction manager for 1 datasource.
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  data:
    redis:
      repositories:
        # Disable redis repositories
        enabled: false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.onixbyte.helix.domain.entity
  type-handlers-package: com.onixbyte.helix.extension.mybatis.handler
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    org.hibernate:
      orm.connections.pooling: off
